version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@octokit/rest"
    versions:
    - 18.1.1
    - 18.2.0
    - 18.2.1
    - 18.3.1
    - 18.3.2
    - 18.3.3
    - 18.3.4
    - 18.3.5
    - 18.4.0
    - 18.5.0
    - 18.5.2
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: simple-git
    versions:
    - 2.35.0
    - 2.35.1
    - 2.35.2
    - 2.36.0
    - 2.36.1
    - 2.36.2
    - 2.37.0
